### ISSUE TITLE
Glass symbols do not accurately show when spirits are active in multiplayer.

### ISSUE THREAD

**Issue by stray-sparks** [Aurocosh/divine-favor#28]
When playing in singleplayer, glass symbols show active spirits correctly. In multiplayer, only the spirits that were active upon leaving singleplayer show as active, no matter what the time is. Presence and invites still work as expected, even though the glass symbol doesn't show the spirit as active. I got Romol's attention and successfully got his invite even though the glass symbols only showed Neblaze and Redwind as active.

**Comment by Aurocosh** [comment]
Unfortunately i think that i cannot fix this issue. In minecraft there is no global time and each dimension has its own time. I am using time of the overworld as global time and on server it is working fine since server has access to all dimensions and can access overworld dimension at any time. On client side however you can't access all dimensions at any time. It seems you only have access to the dimension player is currently in and because of this i cannot access time of overworld freely. I tried for a while, but couldn't figure out a way to keep track of overworld time on client side.

I will remove status of spirit from tooltip of Glass Symbols because it shows incorrect information about spirit activity. It is not really a fix, but it is better then displaying incorrect and confusing information.

You can still use right click with Glass Symbols equipped to find out if spirit is active or not. It is actually handled on server and will display correct information.
