### ISSUE TITLE
Possible Incompatibility with LordCraft

### ISSUE THREAD

**Issue by Crazydude323** [Aurocosh/divine-favor#30]
I'm experiencing a pretty major incompatibility issue with Divine Favor and Lordcraft. When I right-click to use the Arcane Workbench from Lordcraft (a basic crafting-table like block) it immediately kicks me from the server. The server itself does not crash, it just whoever tries to use the Arcane Workbench. I haven't yet tested in single-player to see if the issue exists there.

I'm not 100% on whether this issue is on Divine Favor or Lordcraft's end, so I'm inquiring with both mod developers.

The crash log can be found here: https://paste.dimdev.org/akicobajap.mccrash

**Comment by Aurocosh** [comment]
Thanks for report. I added extra null check in version 1.0.751, so it should not crash anymore. Though this issue is actually caused by LordCraft. I am pretty sure they implemented method getStackInSlot somewhere incorrectly as it returns null instead of ItemStack.EMPTY. This method should never return null.
