### ISSUE TITLE
The Enderer+ No success in summoning 

### ISSUE THREAD

**Issue by PikaPoro** [Aurocosh/divine-favor#8]
Hey,
I really like your mod, I find it really interesting right now. I'm working my way through the Immaterial guide but I've encountered an issue with crafting the pumpkin head, for summoning the Enderer spirit. Despite using the correct recipe, I cannot seem to craft it whatsoever, there is no option for it. 
I got one from creative mode, and I built the Enderer's altar correctly (it said correct at the top of the screen), I then stayed in the bath with the distorted pearl blend for 15 minutes + of aura, however I still could not summon him. I used ender pearls for teleportation, and stayed around endermen that had spawned around, yet still nothing.
I really really reaaally like this mod, and I hope I can continue it!
Thank youuuu,
~PikaPoro

**Comment by Aurocosh** [comment]
I fixed recipe for ender pupkin in version 1.0.539.

And i am not sure why you can summon endererer. I tested it and his ritual works. Maybe you doing something wrong. Here is how you summon him:
To contact him you need to have Distorted aura effect which you get from Pearl blend in bath. When you have this effect you need to put ender pumpkin on your head and hang out with endermans. After a while effect  Distorted aura  will be replaced with Warping presence. You can check your active potion effects by opening your inventory while ender pumpkin is on your head. When you have warping presence effect you need to throw some ender pearls. He will give you invite after you throw several pearls. 
Important! You need to do all of the above when spirit is active! If spirit is inactive you cant summon him.

Also: You can change his activity time in config files if his activity window is not enough for you.
Also Also: In version 1.0.540 new item was added and summoning rituals were slightly changed. New added item is glass symbol of spirit. There are one for each spirit. When you use this item it tells you if related spirit is currently active and when he will become active if he is not active now. Starting from version 1.0.540 you need this item in order to get invite. When you finish summoning ritual all glass symbols in your inventory will be converted into invites. Now you need enderers symbol to get his invite.  You can read about it in guidebook.

**Comment by PikaPoro** [comment]
Thank you for the quick reply!
Yeah I think I was doing something wrong as I have now managed to get Enderer's invite, thank you for the response!
